services:
  tileserver:
    image: overv/openstreetmap-tile-server:v2.2.0
    container_name: meteo-tileserver
    command: run
    ports:
      - "8081:80"
    shm_size: "256m"
    environment:
      THREADS: 2
      ALLOW_CORS: enabled
    volumes:
      - osm-data:/data/database
      - osm-tiles:/data/tiles
    restart: unless-stopped

volumes:
  osm-data:
  osm-tiles:
